apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-05-terraform-aws-pipeline
  labels:
    app: devops-05-terraform-aws-pipeline
    team: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-05-terraform-aws-pipeline
  template:
    metadata:
      labels:
        app: devops-05-terraform-aws-pipeline
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: devops-05-terraform-aws-pipeline
        image: mimaraslan/devops-05-terraform-aws-pipeline:latest
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000